# Generated by Django 6.0.5 on 2026-05-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUEL', 'Fuel (Scope 1)'), ('ELECTRICITY', 'Electricity (Scope 2)'), ('FLIGHT', 'Flight (Scope 3)'), ('HOTEL', 'Hotel (Scope 3)'), ('CAR_RENTAL', 'Car Rental (Scope 3)'), ('MILEAGE', 'Mileage (Scope 3)')], max_length=20)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('factor_kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'subcategory'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP - Fuel & Procurement'), ('UTILITY', 'Utility - Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=10)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 - Direct'), (2, 'Scope 2 - Indirect (Electricity)'), (3, 'Scope 3 - Value Chain')])),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('CAR_RENTAL', 'Car Rental'), ('MILEAGE', 'Mileage')], max_length=20)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=10)),
                ('raw_description', models.TextField(blank=True)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('raw_unit', models.CharField(max_length=20)),
                ('raw_date_from', models.DateField()),
                ('raw_date_to', models.DateField(blank=True, null=True)),
                ('canonical_quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('canonical_unit', models.CharField(max_length=20)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_by', models.CharField(blank=True, max_length=255)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edit_reason', models.TextField(blank=True)),
                ('flagged_by', models.CharField(blank=True, max_length=255)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.organization')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP - Fuel & Procurement'), ('UTILITY', 'Utility - Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=10)),
                ('upload_type', models.CharField(choices=[('FILE_UPLOAD', 'File Upload'), ('API_PULL', 'API Pull'), ('MANUAL', 'Manual')], default='FILE_UPLOAD', max_length=20)),
                ('filename', models.CharField(blank=True, max_length=500)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSING', 'Parsing'), ('PARSED', 'Parsed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=10)),
                ('row_count', models.IntegerField(default=0)),
                ('parsed_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='emissions.organization')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SapFuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(max_length=50)),
                ('material_description', models.TextField(blank=True)),
                ('material_type', models.CharField(blank=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit', models.CharField(max_length=10)),
                ('plant_code', models.CharField(blank=True, max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=10)),
                ('document_date', models.DateField()),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('cost_center', models.CharField(blank=True, max_length=20)),
                ('emission_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_detail', to='emissions.emissionrecord')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_records', to='emissions.sourceupload')),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='source_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='emissions.sourceupload'),
        ),
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('CAR_RENTAL', 'Car Rental'), ('MILEAGE', 'Mileage'), ('OTHER', 'Other')], max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('trip_purpose', models.TextField(blank=True)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('origin_code', models.CharField(blank=True, max_length=10)),
                ('destination_code', models.CharField(blank=True, max_length=10)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('class_of_service', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], default='ECONOMY', max_length=10)),
                ('hotel_nights', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('employee_name', models.CharField(blank=True, max_length=200)),
                ('emission_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_detail', to='emissions.emissionrecord')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_records', to='emissions.sourceupload')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=50)),
                ('utility_name', models.CharField(blank=True, max_length=100)),
                ('billing_start', models.DateField()),
                ('billing_end', models.DateField()),
                ('consumption_kwh', models.DecimalField(decimal_places=4, max_digits=16)),
                ('peak_demand_kw', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('tariff_code', models.CharField(blank=True, max_length=50)),
                ('meter_start_read', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('meter_end_read', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('read_type', models.CharField(choices=[('ACTUAL', 'Actual'), ('ESTIMATED', 'Estimated')], default='ACTUAL', max_length=10)),
                ('charge_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('emission_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_detail', to='emissions.emissionrecord')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_records', to='emissions.sourceupload')),
            ],
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'status'], name='emissions_e_organiz_a7c7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'source_type'], name='emissions_e_organiz_db4a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'scope'], name='emissions_e_organiz_cfc59b_idx'),
        ),
    ]
